# Generated by Django 4.1.5 on 2023-01-17 12:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('basedata', '0003_alter_address_address_type_alter_address_id_and_more'),
        ('organ', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, null=True, verbose_name='code')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('classification', models.CharField(choices=[('10', '工资'), ('20', '社保'), ('30', '奖金'), ('40', '福利'), ('99', '其他')], default='10', max_length=2, verbose_name='classification')),
                ('plus_or_minus', models.CharField(choices=[('+', '增加'), ('-', '扣款')], default='+', max_length=2, verbose_name='plus or minus')),
                ('required', models.BooleanField(default=0, verbose_name='is required')),
            ],
            options={
                'verbose_name': 'salary item',
                'verbose_name_plural': 'salary items',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'employee transfer',
                'verbose_name_plural': 'employee transfers',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='employee number')),
                ('name', models.CharField(max_length=120, verbose_name='employee name')),
                ('pinyin', models.CharField(blank=True, max_length=120, null=True, verbose_name='pinyin')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('gender', models.CharField(choices=[('0', '未知的性别'), ('1', '男性'), ('2', '女性'), ('9', '未说明的性别')], default='1', max_length=2, verbose_name='gender')),
                ('idcard', models.CharField(max_length=20, verbose_name='id card')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='mail address')),
                ('zipcode', models.CharField(max_length=8, verbose_name='zipcode')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('rank', models.CharField(choices=[('10', '领导班子'), ('11', '副总师（助理）'), ('12', '部门负责人（正职）'), ('13', '部门负责人（副职）'), ('14', '部门内设机构负责人（正职）'), ('15', '部门内设机构负责人（副职）'), ('20', '一级职员'), ('21', '二级职员'), ('22', '三级职员'), ('23', '四级职员'), ('24', '五级职员'), ('25', '六级职员'), ('26', '七级职员'), ('27', '八级职员')], default='00', max_length=2, verbose_name='employee rank')),
                ('ygxs', models.CharField(blank=True, choices=[('1', '劳动合同制（长期）'), ('2', '劳动合同制（短期）'), ('3', '人事代理制'), ('4', '劳务派遣制'), ('5', '非全日制'), ('6', '业务外包'), ('9', '其他')], default='2', max_length=2, null=True, verbose_name='employ ygxs')),
                ('category', models.CharField(blank=True, choices=[('10', '经营者'), ('20', '中层管理人员'), ('21', '一般管理人员'), ('30', '专业技术人员'), ('40', '技能人员'), ('50', '服务人员'), ('90', '其他人员')], default='21', max_length=2, null=True, verbose_name='employ category')),
                ('probation_months', models.CharField(choices=[('0', '无试用期'), ('1', '1个月'), ('2', '2个月'), ('3', '3个月'), ('4', '4个月'), ('5', '5个月'), ('6', '6个月'), ('12', '1年')], default='3', max_length=2, verbose_name='probation months')),
                ('probation_begin', models.DateField(default=datetime.date.today, verbose_name='probation begin')),
                ('probation_end', models.DateField(blank=True, null=True, verbose_name='probation end')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='memo')),
                ('profile', models.FileField(blank=True, null=True, upload_to='hr profile', verbose_name='profile')),
                ('guider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.employee', verbose_name='guider')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organ.position', verbose_name='designate position')),
            ],
            options={
                'verbose_name': 'employee entry',
                'verbose_name_plural': 'employee entries',
                'permissions': (('modify_salary_item', 'modify salary item'),),
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(blank=True, null=True, verbose_name='begin date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='modifier')),
                ('creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='creation')),
                ('modification', models.DateTimeField(auto_now=True, null=True, verbose_name='modification')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.employee', verbose_name='employee')),
            ],
            options={
                'verbose_name': 'employee departure',
                'verbose_name_plural': 'employee departures',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculate_way', models.CharField(choices=[('10', '固定值'), ('20', '比例值'), ('30', '计算值')], default='10', max_length=2, verbose_name='calculate way')),
                ('fixed_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='fixed value')),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='base value')),
                ('org_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='org percent')),
                ('employee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='employee percent')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='basedata.employee', verbose_name='employee')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr.entry', verbose_name='employee entry')),
                ('salary_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr.salaryitem', verbose_name='salary item')),
            ],
            options={
                'verbose_name': 'salary item',
                'verbose_name_plural': 'salary item',
                'unique_together': {('entry', 'salary_item')},
            },
        ),
    ]
